### ISSUE TITLE
Problema na autenticação

### ISSUE THREAD

**Issue by rlacerda83** [caiovaccaro/phonegap.facebook.inappbrowser#24]
Fala, tudo certo cara?

Baixei teu js pra fazer um teste em uma aplicação que vai rodar em celulares androids/ios.

Aparentemente o login é feito com sucesso, só que aparece uma pagina em branco escrito:
Success
AVISO DE SEGURANÇA: trate a URL acima com o mesmo sigilo que você trata sua senha e não a compartilhe com ninguém.

Fica nessa tela e não volta pro APP.

Meu código ta aqui: https://github.com/rlacerda83/face3
Abraço

**Comment by caiovaccaro** [comment]
Conseguiu alguma informação? Quando conseguir posta aqui. Abs!

**Comment by caiovaccaro** [comment]
Closing for lack of information.
