### ISSUE TITLE
Access Token Null Problem

### ISSUE THREAD

**Issue by pfdundar** [caiovaccaro/phonegap.facebook.inappbrowser#26]
Hi,
When I login Facebook, it doesnt return success and access token value.

**Comment by caiovaccaro** [comment]
Hello!

Can you paste your code on pastebin and reply with the link?

Thank you.

**Comment by pfdundar** [comment]
http://pastebin.com/DP8UGh78

It connects to the facebook and wants me to login. There is no problem here.
But I cant see access token on the console screen and when I alert it, it gives me null.

**Comment by caiovaccaro** [comment]
Hi,

I see a few problems.

1. It is better if you don't use localhost as a redirect url
2. The line 7 should be removed, since userInfo is already executed automatically
3. I can't see where are you alerting the access_token. Is this the complete code?

Thanks.

**Comment by caiovaccaro** [comment]
Hello @pfdundar , any updates on this?
