### ISSUE TITLE
Delay when opening inAppBrowser

### ISSUE THREAD

**Issue by leouze** [caiovaccaro/phonegap.facebook.inappbrowser#27]
Hi @caiovaccaro !
Thanks for this plugin, its easy to integrate facebook on our Cordova Apps. Its great!
But I've ran into some couple of problems.

When I try to tap the button with the function to call facebook login via inappbrowser, there's a delay between tapping and showing of the window.

Here's the log from XCode that might help:

App[11870:927277] THREAD WARNING: ['InAppBrowser'] took '11.455078' ms. Plugin should use a background thread.

Hope you can help me on this one. :)

**Comment by caiovaccaro** [comment]
Hello @leouze !

I don't think that using a background thread is the thing. It is used when you want to run tasks while your app is not upfront for example.

Have you tried [fastclick](https://github.com/ftlabs/fastclick)?

Other than that, it does have a small delay that is normal.

**Comment by caiovaccaro** [comment]
Hi @leouze , any updates on this issue?

**Comment by leouze** [comment]
Hi @caiovaccaro , the delay is not 300ms so the fast click is not actually the solution.
The delay is about 1500ms or more. But don't worry anymore I think it's normal due to the fact that the inappbrowser is not loaded until the facebook button is tapped.

**Comment by caiovaccaro** [comment]
Thanks for the feedback @leouze !
