### ISSUE TITLE
Query about redirectURL

### ISSUE THREAD

**Issue by Marko1985** [caiovaccaro/phonegap.facebook.inappbrowser#29]
Hi,

I first place, thank you by this code, its very usable.
I have a doubt. I fill this var 
FacebookInAppBrowser.settings.redirectUrl = 'http://localhost/welcome_register.html';
But the aplication always returns to index.html 
Another question is how I could manage for go to specific page indoor a html file (html file with multiple pages phonegap)

Thanks in advance for your help.
Kindest Regards.

**Comment by Marko1985** [comment]
Autorequest: 
Works redirecting to my domain, the app close automatically InAppBrowser and parse the data to JSON.

**Comment by caiovaccaro** [comment]
Hi there! Thank you for creating this issue. 

Actually this is not how the redirectUrl works. The redirectUrl only works inside the InAppBrowser plugin (the new window that opens above your app). Its purpose is for javascript to identify when Facebook ends its process.

At the end the window will always close and return to the app. So if you want to redirect you should do it yourself.

Phonegap apps does not have urls or address bar in the same way a web page does. So you should work with it as a SPA (Single Page Application). You need to use AJAX for that or a client-side framework.

Hope it helps!

**Comment by Marko1985** [comment]
Thank you! This point working and closed.
